const Command = require('../Structures/Command.js');
const superagent = require("superagent");

module.exports = class extends Command {

	constructor(...args) {
		super(...args, {
			aliases: ['meme']
		});
    }


// eslint-disable-next-line no-unused-vars
async run(message, bot) {
    let msg = await message.channel.send("Generating...")

    let {body} = await superagent
    .get(`https://meme-api.herokuapp.com/gimme`)
    //console.log(body.file)
    if(!{body}) return message.channel.send("I broke! Try again.")

        let mEmbed = new Discord.MessageEmbed()
        .setColor('#42b9f5')
        .setAuthor(body.title, message.guild.iconURL)
        .setImage(body.url)
        .setTimestamp()
        .setFooter(`Generated By Vitex Server`, 'https://cdn.discordapp.com/icons/728622524702916678/caa55d2e799726fbb9025843e6445f9a.png')

        message.channel.send({embed: mEmbed});
        console.log(`Meme Generated by ${message.author.tag} for ${message.guild.name} ✅ \n`);

        msg.delete();
}
}